# Generated by Django 5.1 on 2024-08-24 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Viagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_viagem', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('data_ida', models.DateField()),
                ('data_retorno', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Destino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_destino', models.CharField(max_length=255)),
                ('viagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinos', to='viagem.viagem')),
            ],
        ),
    ]
