# Generated by Django 5.1 on 2024-08-24 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('viagem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperatura', models.FloatField()),
                ('condicoes_climaticas', models.CharField(max_length=255)),
                ('viagem', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='viagem.viagem')),
            ],
        ),
    ]
